##Read in all the data
stest <- read.table("subject_test.txt")
Xtest <- read.table("X_test.txt")
ytest <- read.table("y_test.txt")
features <- read.table("features.txt")
activities <- read.table("activity_labels.txt")
strain <- read.table("subject_train.txt")
Xtrain <- read.table("X_train.txt")
ytrain <- read.table("y_train.txt")

##Assign column names
names(Xtest) <- features[,2] 
names(Xtrain) <- features[,2] 
names(ytrain) <- ("activity")
names(ytest) <- ("activity")
names(stest) <- ("subject")
names(strain) <- ("subject")

## combine the X, y and subject files for test and train

tests <- cbind(Xtest, ytest, stest)
trains <- cbind(Xtrain, ytrain, strain)

#combine the two data sets
combined <- rbind(tests, trains) 

##Give good names to activities
combined$activity[which(combined$activity=="1")]<-"WALKING"
combined$activity[which(combined$activity=="2")]<-"WALKING_UPSTAIRS"
combined$activity[which(combined$activity=="3")]<-"WALKING_DOWNSTAIRS"
combined$activity[which(combined$activity=="4")]<-"SITTING"
combined$activity[which(combined$activity=="5")]<-"STANDING"
combined$activity[which(combined$activity=="6")]<-"LAYING"

##Remove odd characters from column names 
names(combined) <- gsub("\\(", "",  names(combined))
names(combined) <- gsub("\\)", "",  names(combined))
names(combined) <- gsub("\\-", "",  names(combined))

##Extract measurements on mean and standard deviation for each measurement

library(reshape2)
combinedMelt <- melt(combined, id=c("activity","subject"), measure.vars=c(grep("mean()", colnames(combined)), grep("std()", colnames(combined))))

##Cast into table with activity, subject, and means of columns

combinedData <- dcast(combinedMelt, subject + activity ~ variable, mean)

## Outputs a text file called combinedData.txt containing the tidy and wide data set generated by the above script

write.table(combinedData, "combinedData.txt", sep="\t")

##need to and write up readme and codebook, then upload it all ##to github

